// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {config} from '../models';
import {models} from '../models';
import {time} from '../models';

export function CreateExam(arg1:number,arg2:string):Promise<services.ExamStartResponse>;

export function GetExamConfig(arg1:string):Promise<config.ExamConfig>;

export function GetExamQuestions(arg1:number):Promise<Array<models.ExamQuestionDetail>>;

export function GetExamRecordByID(arg1:number):Promise<models.ExamRecord>;

export function GetExamResult(arg1:number):Promise<services.ExamResult>;

export function GetUserExamRecords(arg1:number,arg2:string,arg3:number):Promise<Array<models.ExamRecord>>;

export function InvalidateExam(arg1:number):Promise<void>;

export function SubmitExam(arg1:number,arg2:Record<number, services.UserAnswer>,arg3:time.Time):Promise<services.ExamResult>;
