// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateExam(arg1, arg2) {
  return window['go']['services']['ExamService']['CreateExam'](arg1, arg2);
}

export function GetExamConfig(arg1) {
  return window['go']['services']['ExamService']['GetExamConfig'](arg1);
}

export function GetExamQuestions(arg1) {
  return window['go']['services']['ExamService']['GetExamQuestions'](arg1);
}

export function GetExamRecordByID(arg1) {
  return window['go']['services']['ExamService']['GetExamRecordByID'](arg1);
}

export function GetExamResult(arg1) {
  return window['go']['services']['ExamService']['GetExamResult'](arg1);
}

export function GetUserExamRecords(arg1, arg2, arg3) {
  return window['go']['services']['ExamService']['GetUserExamRecords'](arg1, arg2, arg3);
}

export function InvalidateExam(arg1) {
  return window['go']['services']['ExamService']['InvalidateExam'](arg1);
}

export function SubmitExam(arg1, arg2, arg3) {
  return window['go']['services']['ExamService']['SubmitExam'](arg1, arg2, arg3);
}
