// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavoriteQuestion(arg1, arg2, arg3) {
  return window['go']['services']['FavoriteService']['AddFavoriteQuestion'](arg1, arg2, arg3);
}

export function ClearUserFavorites(arg1) {
  return window['go']['services']['FavoriteService']['ClearUserFavorites'](arg1);
}

export function ClearUserFavoritesByCategory(arg1, arg2) {
  return window['go']['services']['FavoriteService']['ClearUserFavoritesByCategory'](arg1, arg2);
}

export function GetFavoriteCount(arg1, arg2) {
  return window['go']['services']['FavoriteService']['GetFavoriteCount'](arg1, arg2);
}

export function GetFavoriteQuestions(arg1, arg2) {
  return window['go']['services']['FavoriteService']['GetFavoriteQuestions'](arg1, arg2);
}

export function IsQuestionFavorited(arg1, arg2) {
  return window['go']['services']['FavoriteService']['IsQuestionFavorited'](arg1, arg2);
}

export function RemoveFavoriteQuestion(arg1, arg2) {
  return window['go']['services']['FavoriteService']['RemoveFavoriteQuestion'](arg1, arg2);
}
