// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddFavoriteQuestion(arg1:number,arg2:number,arg3:string):Promise<boolean>;

export function ClearUserFavorites(arg1:number):Promise<void>;

export function ClearUserFavoritesByCategory(arg1:number,arg2:string):Promise<void>;

export function GetFavoriteCount(arg1:number,arg2:string):Promise<number>;

export function GetFavoriteQuestions(arg1:number,arg2:string):Promise<Array<models.Question>>;

export function IsQuestionFavorited(arg1:number,arg2:number):Promise<boolean>;

export function RemoveFavoriteQuestion(arg1:number,arg2:number):Promise<boolean>;
