// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImportStats() {
  return window['go']['services']['ImportService']['GetImportStats']();
}

export function ImportFromFileContent(arg1, arg2) {
  return window['go']['services']['ImportService']['ImportFromFileContent'](arg1, arg2);
}

export function ImportQuestions(arg1) {
  return window['go']['services']['ImportService']['ImportQuestions'](arg1);
}

export function ProcessFileContent(arg1, arg2) {
  return window['go']['services']['ImportService']['ProcessFileContent'](arg1, arg2);
}

export function ProcessUnifiedData(arg1) {
  return window['go']['services']['ImportService']['ProcessUnifiedData'](arg1);
}

export function ResetDatabase() {
  return window['go']['services']['ImportService']['ResetDatabase']();
}

export function SetContext(arg1) {
  return window['go']['services']['ImportService']['SetContext'](arg1);
}
