// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function GetImportStats():Promise<Record<string, any>>;

export function ImportFromFileContent(arg1:string,arg2:string):Promise<services.ImportResult>;

export function ImportQuestions(arg1:Array<models.Question>):Promise<services.ImportResult>;

export function ProcessFileContent(arg1:string,arg2:string):Promise<services.ImportResult>;

export function ProcessUnifiedData(arg1:string):Promise<services.ImportResult>;

export function ResetDatabase():Promise<boolean>;
