// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddErrorQuestion(arg1, arg2, arg3) {
  return window['go']['services']['PracticeService']['AddErrorQuestion'](arg1, arg2, arg3);
}

export function GetErrorQuestions(arg1, arg2) {
  return window['go']['services']['PracticeService']['GetErrorQuestions'](arg1, arg2);
}

export function GetPracticeProgress(arg1, arg2) {
  return window['go']['services']['PracticeService']['GetPracticeProgress'](arg1, arg2);
}

export function GetQuestionsByCategory(arg1) {
  return window['go']['services']['PracticeService']['GetQuestionsByCategory'](arg1);
}

export function GetRandomQuestions(arg1, arg2, arg3) {
  return window['go']['services']['PracticeService']['GetRandomQuestions'](arg1, arg2, arg3);
}

export function ResetProgress(arg1, arg2) {
  return window['go']['services']['PracticeService']['ResetProgress'](arg1, arg2);
}

export function SavePracticeProgress(arg1, arg2, arg3) {
  return window['go']['services']['PracticeService']['SavePracticeProgress'](arg1, arg2, arg3);
}

export function ShuffleOptions(arg1) {
  return window['go']['services']['PracticeService']['ShuffleOptions'](arg1);
}
