// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddErrorQuestion(arg1:number,arg2:string,arg3:number):Promise<boolean>;

export function GetErrorQuestions(arg1:number,arg2:string):Promise<Array<models.Question>>;

export function GetPracticeProgress(arg1:number,arg2:string):Promise<number>;

export function GetQuestionsByCategory(arg1:string):Promise<Array<models.Question>>;

export function GetRandomQuestions(arg1:string,arg2:number,arg3:number):Promise<Array<models.Question>>;

export function ResetProgress(arg1:number,arg2:string):Promise<void>;

export function SavePracticeProgress(arg1:number,arg2:string,arg3:number):Promise<void>;

export function ShuffleOptions(arg1:Array<models.Question>):Promise<Array<models.Question>>;
