// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function DeleteQuestion(arg1:number):Promise<void>;

export function ExportToCSV(arg1:string):Promise<boolean>;

export function ExportToExcel(arg1:string):Promise<boolean>;

export function ExportToJSON(arg1:string):Promise<boolean>;

export function GetFilteredRecordsCount(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<number>;

export function GetPageData(arg1:number,arg2:number,arg3:string,arg4:boolean,arg5:boolean,arg6:boolean):Promise<services.PageDataResult>;

export function GetQuestionByID(arg1:number):Promise<models.Question>;

export function UpdateQuestion(arg1:number,arg2:Record<string, any>):Promise<void>;
