// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteQuestion(arg1) {
  return window['go']['services']['QuestionsBankService']['DeleteQuestion'](arg1);
}

export function ExportToCSV(arg1) {
  return window['go']['services']['QuestionsBankService']['ExportToCSV'](arg1);
}

export function ExportToExcel(arg1) {
  return window['go']['services']['QuestionsBankService']['ExportToExcel'](arg1);
}

export function ExportToJSON(arg1) {
  return window['go']['services']['QuestionsBankService']['ExportToJSON'](arg1);
}

export function GetFilteredRecordsCount(arg1, arg2, arg3, arg4) {
  return window['go']['services']['QuestionsBankService']['GetFilteredRecordsCount'](arg1, arg2, arg3, arg4);
}

export function GetPageData(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['QuestionsBankService']['GetPageData'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetQuestionByID(arg1) {
  return window['go']['services']['QuestionsBankService']['GetQuestionByID'](arg1);
}

export function UpdateQuestion(arg1, arg2) {
  return window['go']['services']['QuestionsBankService']['UpdateQuestion'](arg1, arg2);
}
