// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {services} from '../models';
import {models} from '../models';

export function ClearQuestionBank():Promise<void>;

export function ClearUserData(arg1:number):Promise<void>;

export function DeleteQuestion(arg1:number):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function ExportQuestionsToCSV(arg1:string):Promise<boolean>;

export function ExportQuestionsToExcel(arg1:string):Promise<boolean>;

export function ExportQuestionsToJSON(arg1:string):Promise<boolean>;

export function GetAllExamConfigs():Promise<Record<string, config.ExamConfig>>;

export function GetAllUsers():Promise<Array<Record<string, any>>>;

export function GetAppInfo():Promise<services.AppInfo>;

export function GetDatabaseStats():Promise<Record<string, number>>;

export function GetExamConfig(arg1:string):Promise<config.ExamConfig>;

export function GetFilteredRecordsCount(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<number>;

export function GetQuestionByID(arg1:number):Promise<models.Question>;

export function GetQuestionsPage(arg1:number,arg2:number,arg3:string,arg4:boolean,arg5:boolean,arg6:boolean):Promise<Record<string, any>>;

export function GetUserCount():Promise<number>;

export function ImportQuestions(arg1:string):Promise<services.ImportResult>;

export function ResetDatabase():Promise<void>;

export function UpdateQuestion(arg1:number,arg2:Record<string, any>):Promise<void>;
