// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function CalculateExamStatistics(arg1:Array<models.ExamStatisticsData>):Promise<services.ExamStatisticsResult>;

export function GetCategoryStatistics(arg1:number,arg2:string):Promise<Record<string, any>>;

export function GetExamData(arg1:number,arg2:string,arg3:string):Promise<Array<models.ExamStatisticsData>>;

export function GetUserStatistics(arg1:number):Promise<services.UserStatisticsResult>;
