// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateExamStatistics(arg1) {
  return window['go']['services']['StatisticsService']['CalculateExamStatistics'](arg1);
}

export function GetCategoryStatistics(arg1, arg2) {
  return window['go']['services']['StatisticsService']['GetCategoryStatistics'](arg1, arg2);
}

export function GetExamData(arg1, arg2, arg3) {
  return window['go']['services']['StatisticsService']['GetExamData'](arg1, arg2, arg3);
}

export function GetUserStatistics(arg1) {
  return window['go']['services']['StatisticsService']['GetUserStatistics'](arg1);
}
