// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function GetAllUsers():Promise<Array<models.User>>;

export function GetByID(arg1:number):Promise<models.User>;

export function GetByIDCard(arg1:string):Promise<models.User>;

export function GetByUsername(arg1:string):Promise<models.User>;

export function Login(arg1:string,arg2:string):Promise<services.UserLoginResponse>;
