// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllUsers() {
  return window['go']['services']['UserService']['GetAllUsers']();
}

export function GetByID(arg1) {
  return window['go']['services']['UserService']['GetByID'](arg1);
}

export function GetByIDCard(arg1) {
  return window['go']['services']['UserService']['GetByIDCard'](arg1);
}

export function GetByUsername(arg1) {
  return window['go']['services']['UserService']['GetByUsername'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['services']['UserService']['Login'](arg1, arg2);
}
